-- Table: orders.customers

-- DROP TABLE IF EXISTS orders.customers;

CREATE SCHEMA IF NOT EXISTS orders;

CREATE TABLE IF NOT EXISTS orders.customers
(
    address_id bigint,
    email_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone_id bigint,
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT customers_pkey PRIMARY KEY (id),
    CONSTRAINT fk_customers_phone_id_phones_id FOREIGN KEY (phone_id)
        REFERENCES contacts.phones (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_customers_email_id_emails_id FOREIGN KEY (email_id)
        REFERENCES contacts.emails (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_customers_address_id_addresses_id FOREIGN KEY (address_id)
        REFERENCES contacts.addresses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS orders.customers
    OWNER to postgres;