-- Table: orders.orders

-- DROP TABLE IF EXISTS orders.orders;

CREATE SCHEMA IF NOT EXISTS orders;

CREATE TABLE IF NOT EXISTS orders.orders
(
    total numeric(38,2),
    created_at timestamp(6) without time zone,
    customer_id bigint,
    establishment_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) without time zone,
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fk_orders_establishment_id_restaurants_id FOREIGN KEY (establishment_id)
        REFERENCES establishments.restaurants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_orders_customer_id_customers_id FOREIGN KEY (customer_id)
        REFERENCES orders.customers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT orders_status_check CHECK (status::text = ANY (ARRAY['CREATED'::character varying, 'IN_PREPARATION'::character varying, 'READY'::character varying, 'DELIVERED'::character varying, 'CANCELED'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS orders.orders
    OWNER to postgres;