-- Table: orders.order_items

-- DROP TABLE IF EXISTS orders.order_items;

CREATE TABLE IF NOT EXISTS orders.order_items
(
    quantity integer,
    unit_price numeric(38,2),
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    order_id bigint,
    title character varying(255) COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order_id_orders_id FOREIGN KEY (order_id)
        REFERENCES orders.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS orders.order_items
    OWNER to postgres;