-- Table: orders.products

-- DROP TABLE IF EXISTS orders.products;

CREATE TABLE IF NOT EXISTS orders.products
(
    available boolean,
    price numeric(38,2),
    establishment_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT fk_products_establishment_id_restaurants_id FOREIGN KEY (establishment_id)
        REFERENCES establishments.restaurants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS orders.products
    OWNER to postgres;