-- Table: orders.establishments

-- DROP TABLE IF EXISTS orders.establishments;

CREATE TABLE IF NOT EXISTS orders.establishments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT establishments_pkey PRIMARY KEY (id),
    CONSTRAINT establishments_type_check CHECK (type::text = ANY (ARRAY['RESTAURANT'::character varying, 'PIZZERIA'::character varying, 'SUPERMARKET'::character varying, 'BAR'::character varying, 'COFFEE_SHOP'::character varying, 'SNACK_BAR'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS orders.establishments
    OWNER to postgres;