-- Table: establishments.restaurants

-- DROP TABLE IF EXISTS establishments.restaurants;

CREATE SCHEMA IF NOT EXISTS establishments;

CREATE TABLE IF NOT EXISTS establishments.restaurants
(
    is_deleted boolean,
    address_id bigint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    email_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone_id bigint,
    updated_at timestamp(6) without time zone,
    restaurant_name character varying(256) COLLATE pg_catalog."default" NOT NULL,
    backdrop text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    logo text COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT restaurants_pkey PRIMARY KEY (id),
    CONSTRAINT restaurants_address_id_key UNIQUE (address_id),
    CONSTRAINT restaurants_email_id_key UNIQUE (email_id),
    CONSTRAINT restaurants_phone_id_key UNIQUE (phone_id),
    CONSTRAINT fk_restaurants_phone_id_phones_id FOREIGN KEY (phone_id)
        REFERENCES contacts.phones (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_restaurants_address_id_addresses_id FOREIGN KEY (address_id)
        REFERENCES contacts.addresses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_restaurants_email_id_emails_id FOREIGN KEY (email_id)
        REFERENCES contacts.emails (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT restaurants_type_check CHECK (type::text = ANY (ARRAY['ITALIAN'::character varying, 'JAPANESE'::character varying, 'THAI'::character varying, 'CHINESE'::character varying, 'MEXICAN'::character varying, 'INDIAN'::character varying, 'AMERICAN'::character varying, 'FRENCH'::character varying, 'BRAZILIAN'::character varying, 'MEDITERRANEAN'::character varying, 'SPANISH'::character varying, 'GREEK'::character varying, 'KOREAN'::character varying, 'VIETNAMESE'::character varying, 'TURKISH'::character varying, 'ARABIC'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS establishments.restaurants
    OWNER to postgres;