-- Table: establishments.menus

-- DROP TABLE IF EXISTS establishments.menus;

CREATE TABLE IF NOT EXISTS establishments.menus
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    restaurant_id bigint,
    menu_name character varying(256) COLLATE pg_catalog."default" NOT NULL,
    menu_description text COLLATE pg_catalog."default",
    CONSTRAINT menus_pkey PRIMARY KEY (id),
    CONSTRAINT fk_menus_restaurant_id_restaurants_id FOREIGN KEY (restaurant_id)
        REFERENCES establishments.restaurants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS establishments.menus
    OWNER to postgres;