-- Table: establishments.menu_items

-- DROP TABLE IF EXISTS establishments.menu_items;

CREATE TABLE IF NOT EXISTS establishments.menu_items
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
    ),
    item_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    item_description text COLLATE pg_catalog."default",
    unit_price DECIMAL NOT NULL,
    menu_id bigint,

    CONSTRAINT menu_items_pkey PRIMARY KEY (id),

    CONSTRAINT fk_menu_items_menu FOREIGN KEY (menu_id)
        REFERENCES establishments.menus (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS establishments.menu_items
    OWNER TO postgres;
