-- Table: establishments.showcase_pictures

-- DROP TABLE IF EXISTS establishments.showcase_pictures;

CREATE TABLE IF NOT EXISTS establishments.showcase_pictures
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    menu_item_id bigint,
    base64 text COLLATE pg_catalog."default",
    CONSTRAINT showcase_pictures_pkey PRIMARY KEY (id),
    CONSTRAINT fk_showcase_pictures_menu_item_id_menus_id FOREIGN KEY (menu_item_id)
        REFERENCES establishments.menu_items (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS establishments.showcase_pictures
    OWNER to postgres;