-- Table: establishments.service_times

-- DROP TABLE IF EXISTS establishments.service_times;

CREATE TABLE IF NOT EXISTS establishments.service_times
(
    closes_at time(6) without time zone NOT NULL,
    opens_at time(6) without time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    restaurant_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT service_times_pkey PRIMARY KEY (id),
    CONSTRAINT fk_service_times_restaurant_id_restaurants_id FOREIGN KEY (restaurant_id)
        REFERENCES establishments.restaurants (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS establishments.service_times
    OWNER to postgres;