-- Table: inventory.suppliers

-- DROP TABLE IF EXISTS inventory.suppliers;

CREATE TABLE IF NOT EXISTS inventory.suppliers
(
    moq integer,
    performance_rating numeric(10,2),
    address_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone_id bigint,
    document character varying(14) COLLATE pg_catalog."default" NOT NULL,
    category character varying(255) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    preferred_payment_method character varying(255) COLLATE pg_catalog."default",
    trade_name character varying(255) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT suppliers_pkey PRIMARY KEY (id),
    CONSTRAINT suppliers_address_id_key UNIQUE (address_id),
    CONSTRAINT suppliers_phone_id_key UNIQUE (phone_id),
    CONSTRAINT fk_suppliers_address_id_addresses_id FOREIGN KEY (address_id)
        REFERENCES contacts.addresses (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_suppliers_phone_id_phones_id FOREIGN KEY (phone_id)
        REFERENCES contacts.phones (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT suppliers_category_check CHECK (category::text = ANY (ARRAY['ELECTRONICS'::character varying, 'FOOD_BEVERAGE'::character varying, 'OFFICE_SUPPLIES'::character varying, 'AUTOMOTIVE'::character varying, 'APPAREL'::character varying, 'RAW_MATERIALS'::character varying, 'PACKAGING'::character varying, 'MACHINERY'::character varying, 'FURNITURE'::character varying, 'CLEANING_SUPPLIES'::character varying, 'MEDICAL_SUPPLIES'::character varying, 'CONSTRUCTION'::character varying, 'IT_SERVICES'::character varying, 'MARKETING_SERVICES'::character varying, 'PROFESSIONAL_SERVICES'::character varying, 'AGRICULTURE'::character varying, 'PRINTING'::character varying, 'PRODUCE'::character varying, 'MEAT_SEAFOOD'::character varying, 'DAIRY'::character varying, 'BAKERY'::character varying, 'GROCERY'::character varying, 'BEVERAGES'::character varying, 'CONDIMENTS'::character varying, 'FROZEN_FOOD'::character varying, 'SANITATION'::character varying, 'EQUIPMENT'::character varying, 'INGREDIENTS'::character varying, 'SEAFOOD'::character varying]::text[])),
    CONSTRAINT suppliers_preferred_payment_method_check CHECK (preferred_payment_method::text = ANY (ARRAY['CASH'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'BANK_TRANSFER'::character varying, 'DIGITAL_WALLET'::character varying, 'ELECTRONIC_CHECK'::character varying, 'COD'::character varying, 'FINANCING'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS inventory.suppliers
    OWNER to postgres;