CREATE SCHEMA IF NOT EXISTS contacts;

CREATE TABLE IF NOT EXISTS contacts.addresses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    city character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    local_number character varying(255) COLLATE pg_catalog."default",
    neighborhood character varying(255) COLLATE pg_catalog."default",
    state character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    zipcode character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT addresses_pkey PRIMARY KEY (id),
    CONSTRAINT addresses_type_check CHECK (type::text = ANY (ARRAY['RESIDENTIAL'::character varying, 'COMMERCIAL'::character varying, 'CORRESPONDENCE'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS contacts.addresses
    OWNER to postgres;