-- Table: contacts.emails

-- DROP TABLE IF EXISTS contacts.emails;

CREATE TABLE IF NOT EXISTS contacts.emails
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT emails_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS contacts.emails
    OWNER to postgres;