-- Table: contacts.phones

-- DROP TABLE IF EXISTS contacts.phones;

CREATE TABLE IF NOT EXISTS contacts.phones
(
    prefix character varying(3) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    phone_number character varying(16) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT phones_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS contacts.phones
    OWNER to postgres;