TRUNCATE flyway_schema_history CASCADE

TRUNCATE addresses CASCADE;
TRUNCATE certifications CASCADE;
TRUNCATE goods CASCADE;
TRUNCATE menu_items CASCADE;
TRUNCATE menus CASCADE;
TRUNCATE notes CASCADE;
TRUNCATE phones CASCADE;
TRUNCATE emails CASCADE;
TRUNCATE service_times CASCADE;
TRUNCATE restaurants CASCADE;
TRUNCATE showcase_pictures CASCADE;
TRUNCATE suppliers CASCADE;

DROP TABLE addresses CASCADE;
DROP TABLE certifications CASCADE;
DROP TABLE goods CASCADE;
DROP TABLE menu_items CASCADE;
DROP TABLE menus CASCADE;
DROP TABLE notes CASCADE;
DROP TABLE phones CASCADE;
DROP TABLE emails CASCADE;
DROP TABLE service_times CASCADE;
DROP TABLE restaurants CASCADE;
DROP TABLE showcase_pictures CASCADE;
DROP TABLE suppliers CASCADE;
DROP TABLE patents CASCADE;
